update

diff --git a/hlapers b/hlapers
--- a/hlapers
+++ b/hlapers
@@ -5,8 +5,8 @@ usage() {
     echo "Usage: hlapers [modes]"
     echo ""
     printf "%-20s %s\n" "prepare-ref" "Prepare transcript fasta files."
-    printf "%-20s %s\n" "index" "Create index for STARsalmon or kallisto."
-    printf "%-20s %s\n" "quant" "Quantify expression with STARsalmon or kallisto pipelines."
+    printf "%-20s %s\n" "index" "Create index for read alignment."
+    printf "%-20s %s\n" "genotype" "Infer HLA genotypes."
 }
 
 usage_prepare() {
@@ -22,13 +22,31 @@ usage_index() {
     echo "Usage: hlapers index [options]"
     echo ""
     printf "%-20s %s\n" "-t | --transcripts" "Fasta with Gencode transcript sequences."
-    printf "%-20s %s\n" "-p | --threads" "Number of threads"
-    printf "%-20s %s\n" "-o | --out" "Output directory"
+    printf "%-20s %s\n" "-p | --threads" "Number of threads."
+    printf "%-20s %s\n" "-o | --out" "Output directory."
+}
+
+
+usage_genotype() {
+    echo "Usage: hlapers genotype [options]"
+    echo ""
+    printf "%-20s %s\n" "-i | --index" "Index generated by 'hlapers index'."
+    printf "%-20s %s\n" "-t | --transcripts" "Fasta with Gencode transcripts sequences used for 'hlapers index'." 
+    printf "%-20s %s\n" "-m | --mhccoords" "Genomics coordinates of the MHC region."
+    printf "%-20s %s\n" "-b | --bam" "BAM file with Genomic alignments."
+    printf "%-20s %s\n" "-p | --threads" "Number of threads."
+    printf "%-20s %s\n" "-o | --outprefix" "Output prefix name."
 }
 
 
 # Mode functions
 run_prepref () {
+    
+    if [ "$#" == 0 ]; then
+	usage_prepare
+	exit 1
+    fi
+    
     while [ "$#" -gt 0 ]; do
         case "$1" in
         -h | --help)
@@ -64,6 +82,12 @@ run_prepref () {
 
 
 run_index() {
+    
+    if [ "$#" == 0 ]; then
+	usage_index
+	exit 1
+    fi
+    
     while [ "$#" -gt 0 ]; do
         case "$1" in
         -h | --help)
@@ -94,10 +118,65 @@ run_index() {
     mkdir -p $out/STARMHC
     mkdir -p $out/SalmonMHC
 
-    STAR --runThreadN $threads --runMode GenomeGenerate --genomeDir $out/STARMHC \
-	--genomeFastaFiles $transcripts --genomeChrBinNbits 10 --genomeSAindexNbases 11
-
+    STAR --runThreadN $threads --runMode genomeGenerate \
+	--genomeDir $out/STARMHC --genomeFastaFiles $transcripts \
+	--genomeChrBinNbits 10 --genomeSAindexNbases 11
 }
+
+run_genotype() {
+
+    if [ "$#" == 0 ]; then
+        usage_genotype
+        exit 1
+    fi
+
+    while [ "$#" -gt 0 ]; do
+	case "$1" in
+	    -h | --help)
+		usage_genotype
+		exit
+		;;
+	    -i | --index)
+		index="$2"
+		shift 2
+		;;
+	    -t | --transcripts)
+		transcripts="$2"
+		shift 2
+		;;
+	    -m | --mhccoords)
+		hlacoords="$2"
+		shift 2
+		;;
+	    -b | --bam)
+		bam="$2"
+		shift 2
+		;;
+	    -p | --threads)
+		threads="$2"
+		shift 2
+		;;
+	    -o | --out)
+		outprefix="$2"
+		shift 2
+		;;
+	    *)
+		echo "ERROR: unknown parameter $1"
+		usage_genotype
+		exit 1
+		;;
+	esac
+    done
+
+    ./script/run_genotyping.sh $bam $index $transcripts $hlacoords $outprefix $threads
+}
+
+
+# main
+if [ "$#" == 0 ]; then
+    usage
+    exit 1
+fi
 
 
 while [[ $# -gt 0 ]]
@@ -117,6 +196,12 @@ do
     index)
 	shift
 	run_index "$@"
+	break
+	;;
+
+    genotype)
+	shift
+	run_genotype "$@"
 	break
 	;;
 
