add bam2fq and take fastq as input

diff --git a/hlapers b/hlapers
--- a/hlapers
+++ b/hlapers
@@ -6,6 +6,7 @@ usage() {
     echo ""
     printf "%-20s %s\n" "prepare-ref" "Prepare transcript fasta files."
     printf "%-20s %s\n" "index" "Create index for read alignment."
+    printf "%-20s %s\n" "bam2fq" "Convert BAM to fastq."
     printf "%-20s %s\n" "genotype" "Infer HLA genotypes."
     printf "%-20s %s\n" "quant" "Quantify HLA expression."
 }
@@ -27,14 +28,13 @@ usage_index() {
     printf "%-20s %s\n" "-o | --out" "Output directory."
 }
 
-
 usage_genotype() {
     echo "Usage: hlapers genotype [options]"
     echo ""
     printf "%-20s %s\n" "-i | --index" "Index generated by 'hlapers index'."
     printf "%-20s %s\n" "-t | --transcripts" "Fasta with Gencode transcripts sequences used for 'hlapers index'." 
-    printf "%-20s %s\n" "-m | --mhccoords" "Genomics coordinates of the MHC region."
-    printf "%-20s %s\n" "-b | --bam" "BAM file with Genomic alignments."
+    printf "%-20s %s\n" "-1 | --fq1" "MHC Fastq for READ 1 sorted by read id."
+    printf "%-20s %s\n" "-2 | --fq2" "MHC Fastq for READ 2 sorted by read id."
     printf "%-20s %s\n" "-p | --threads" "Number of threads."
     printf "%-20s %s\n" "-o | --outprefix" "Output prefix name."
 }
@@ -42,11 +42,20 @@ usage_genotype() {
 usage_quant() {
     echo "Usage: hlapers quant [options]"
     echo ""
-    printf "%-20s %s\n" "-b | --bam" "BAM file."
     printf "%-20s %s\n" "-t | --transcripts" "Reference transcripts directory."
     printf "%-20s %s\n" "-f | --hlafasta" "Fasta with the individual's HLA sequences."
+    printf "%-20s %s\n" "-1 | --fq1" "Fastq for READ 1 sorted by read id."
+    printf "%-20s %s\n" "-2 | --fq2" "Fastq for READ 2 sorted by read id."
     printf "%-20s %s\n" "-p | --threads" "Number of threads."
     printf "%-20s %s\n" "-o | --out" "Output prefix name."
+}
+
+usage_bam2fq() {
+    echo "Usage: hlapers bam2fq [options]"
+    echo ""
+    printf "%-20s %s\n" "-m | --mhc-coords" "Genomic coordinates of the MHC region in chrN:start-end format if MHC fastq is desired."
+    printf "%-20s %s\n" "-b | --bam" "BAM file."
+    printf "%-20s %s\n" "-o | --outprefix" "Output prefix name."
 }
 
 # Mode functions
@@ -124,13 +133,7 @@ run_index() {
         esac
     done
     
-    mkdir -p $out
-    mkdir -p $out/STARMHC
-    mkdir -p $out/SalmonMHC
-
-    STAR --runThreadN $threads --runMode genomeGenerate \
-	--genomeDir $out/STARMHC --genomeFastaFiles $transcripts \
-	--genomeChrBinNbits 10 --genomeSAindexNbases 11
+    ./script/run_starindex.sh $transcripts $out $threads
 }
 
 run_genotype() {
@@ -154,13 +157,13 @@ run_genotype() {
 		transcripts="$2"
 		shift 2
 		;;
-	    -m|--mhccoords)
-		hlacoords="$2"
+	    -1|--fq1)
+		fq1="$2"
 		shift 2
 		;;
-	    -b|--bam)
-		bam="$2"
-		shift 2
+	    -2|--fq2)
+		fq2="$2"
+		shift  2
 		;;
 	    -p|--threads)
 		threads="$2"
@@ -178,7 +181,7 @@ run_genotype() {
 	esac
     done
 
-    ./script/run_genotyping.sh $bam $index $transcripts $hlacoords $outprefix $threads
+    ./script/run_genotyping.sh $index $transcripts $fq1 $fq2 $outprefix $threads
 }
 
 run_quant() {
@@ -193,16 +196,20 @@ run_quant() {
 		usage_quant
 		exit
 		;;
-	    -b|--bam)
-		bam="$2"
-		shift 2
-		;;
 	    -t|--transcripts)
 		transcripts="$2"
 		shift 2
 		;;
 	    -f|--hlafasta)
 		hlafasta="$2"
+		shift 2
+		;;
+	    -1|--fq1)
+		fq1="$2"
+		shift 2
+		;;
+	    -2|--fq2)
+		fq2="$2"
 		shift 2
 		;;
 	    -p|--threads)
@@ -221,9 +228,53 @@ run_quant() {
 	esac
     done
 
-    ./script/run_quant.sh $bam $transcripts $hlafasta $outprefix $threads
+    ./script/run_quant.sh $transcripts $hlafasta $fq1 $fq2 $outprefix $threads
 }
 
+run_bam2fq() {
+    if [[ "$#" -eq 0 ]]; then
+        usage_bam2fq
+        exit 1
+    fi
+
+    while [[ "$#" -gt 0 ]]; do
+	case "$1" in
+	    -h|--help)
+		usage_quant
+		exit
+		;;
+	    -b|--bam)
+		bam="$2"
+		shift 2
+		;;
+	    -m|--mhc)
+		if [[ -n "$2" ]] && [[ "$2" != -* ]]; then
+		    mhc="$2"
+		    shift 2
+		else
+		    echo "ERROR: missing MHC coordinates."
+		    exit 1
+		fi
+		;;
+	    -o|--out)
+		out="$2"
+		shift 2
+		;;
+	    *)
+		echo "ERROR: unknown parameter $1"
+		usage_bam2fq
+		exit 1
+		;;
+	esac
+    done
+
+    if [[ -n "$mhc" ]]; then
+	./script/run_bam2fq_mhc.sh $bam $mhc $out
+    else
+	./script/run_bam2fq.sh $bam $out
+    fi
+
+}
 
 # main
 if [[ "$#" -eq 0 ]]; then
@@ -263,7 +314,11 @@ do
 	run_quant "$@"
 	break
 	;;
-
+    bam2fq)
+	shift
+	run_bam2fq "$@"
+	break
+	;;
     *)
 	echo "ERROR: unknown parameter $1"
 	usage
